StudioBooking/Areas/Admin/Models/TeamViewModel.cs
using StudioBooking.DTO;

namespace StudioBooking.Areas.Admin.Models
{
    public class TeamViewModel
    {
        public TeamDTO Team { get; set; }
        public bool Result { get; set; }
        public string? ErrorMessage { get; set; }
        public TeamViewModel()
        {
            Team = new TeamDTO();
        }
    }
}

StudioBooking/Areas/Admin/Controllers/TeamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudioBooking.Areas.Admin.Models;
using StudioBooking.Data;
using StudioBooking.Data.Models;
using StudioBooking.DTO;
using StudioBooking.Infrastructure;

namespace StudioBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TeamController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly string _filePath;
        public TeamController(UserManager<ApplicationUser> userManager, ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment) : base(userManager)
        {
            _context = applicationDbContext;
            _webHostEnvironment = webHostEnvironment;
            _filePath = _webHostEnvironment.WebRootPath + AppConfig.TeamImageUrl.Replace("/", "\\");
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new TeamViewModel());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var teamViewModel = new TeamViewModel
            {
                Team = await TeamDTO.GetTeam(_context, id)
            };
            return View("Create", teamViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveTeam(TeamViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var teamInDb = await _context.Teams.FirstOrDefaultAsync(c => c.Id == model.Team.Id && !c.IsDelete);
                    if (teamInDb == null)
                    {

                        var team = new Team
                        {
                            Name = model.Team.Name,
                            Professions = model.Team.Professions,
                            Description = model.Team.Description,
                            CreatedBy = GetUserId(),
                            CreatedDate = Defaults.GetDateTime(),
                            ModifiedBy = GetUserId(),
                            ModifiedDate = Defaults.GetDateTime(),
                            IsActive = true,
                            Image = model.Team.ImageName != null ? new Common().UploadedFile(model.Team.ImageName, _filePath) : string.Empty,
                        };
                        await _context.Teams.AddAsync(team);
                    }
                    else
                    {
                        teamInDb.Name = model.Team.Name;
                        teamInDb.Description = model.Team.Description;
                        teamInDb.Professions = model.Team.Professions;
                        teamInDb.ModifiedBy = GetUserId();
                        teamInDb.ModifiedDate = Defaults.GetDateTime();
                        teamInDb.Image = model.Team.ImageName != null ? new Common().UploadedFile(model.Team.ImageName, _filePath) : teamInDb.Image;
                    }
                    await _context.SaveChangesAsync();
                    model.Result = true;
                }
                catch (Exception ex)
                {
                    model.ErrorMessage = ex.Message;
                    model.Result = false;
                }
            }
            return View("Create", model);
        }


        [HttpGet]
        public async Task<IActionResult> GetTeams()
        {
            var teams = await TeamDTO.GetTeams(_context, true);
            return Ok(new { data = teams });
        }
    }
}

StudioBooking/Areas/Admin/Views/Team/Create.cshtml
@using StudioBooking.Infrastructure;
@model StudioBooking.Areas.Admin.Models.TeamViewModel
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Create Team Member
                </h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="/Admin/" class="text-muted">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/Admin/Team" class="text-muted">Team Member</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="Admin/Team/Create" class="text-muted"> @(Model.Team.Id == 0 ? "Create Team Member" : "Update Team Member")</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<!--end::Subheader-->
<div class="card card-custom card-sticky" id="kt_page_sticky_card">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                @(Model.Team.Id == 0 ? "Create Team Member" : "Update Team Member") <i class="mr-2"></i>
                @*<small class="">try to scroll the page</small>*@
            </h3>
        </div>
        <div class="card-toolbar">
            <a href="/Admin/Team" class="btn btn-light-primary font-weight-bolder mr-2">
                <i class="ki ki-long-arrow-back icon-sm"></i>
                Back
            </a>
            <div class="btn-group">
                <button type="button" class="btn btn-primary font-weight-bolder" onclick="submitForm()">
                    <i class="ki ki-check icon-sm"></i>
                    Save
                </button>
            </div>
        </div>
    </div>
    <div class="card-body" style="padding-bottom:0px">
        <!--begin::Form-->
        <form asp-action="SaveTeam" asp-area="Admin" asp-controller="Team" method="post" class="form" enctype="multipart/form-data" id="kt_form">
            @Html.HiddenFor(t => t.Team.Id)
            @Html.HiddenFor(t => t.Team.Image)
            <div class="row">
                <div class="col-xl-2"></div>
                <div class="col-xl-8">
                    <div class="form-group row">
                        <label asp-for="Team.Name" class="col-3">Name</label>
                        <div class="col-9">
                            <input asp-for="Team.Name" class="form-control form-control-solid" required="true" placeholder="Name" />
                            <span asp-validation-for="Team.Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Team.Professions" class="col-3">Professions</label>
                        <div class="col-9">
                            <select id="ProfessionList" class="form-control form-control-solid select2" asp-items="Html.GetEnumSelectList<Enums.Professions>()" multiple="multiple">
                            </select>
                            @Html.HiddenFor(t => t.Team.Professions)
                        </div>
                    </div>
                    @*<div class="form-group row">
                    <label asp-for="Team.Professions" class="col-3">Professions</label>
                    <div class="col-9">
                    <input asp-for="Team.Professions" class="form-control form-control-solid" required="true" placeholder="Professions" />
                    <span asp-validation-for="Team.Professions" class="text-danger"></span>
                    </div>
                    </div>*@
                    <div class="form-group row">
                        <label asp-for="Team.Description" class="col-3">Description</label>
                        <div class="col-9">
                            <textarea asp-for="Team.Description" class="form-control form-control-solid" placeholder="Description" rows="2"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Team.Image" class="col-3">Image</label>
                        <div class="col-9">
                            <div class="image-input image-input-outline" id="kt_image_1">
                                <div class="image-input-wrapper" style="background-image: url('@(string.IsNullOrEmpty(Model.Team.Image) ? Defaults.UploadImage : (AppConfig.TeamImageUrl + Model.Team.Image))')"></div>
                                <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Upload Image">
                                    <i class="fa fa-pen icon-sm text-muted"></i>
                                    <input asp-for="Team.ImageName" accept=".png, .jpg, .jpeg" class="custom-file-input" />
                                </label>
                                <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Discard Image">
                                    <i class="ki ki-bold-close icon-xs text-muted"></i>
                                </span>
                            </div>
                            <span class="form-text text-muted">Allowed file types:  png, jpg, jpeg.</span>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2"></div>
            </div>
        </form>
        <!--end::Form-->
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        var sourceUpdated = false;
        $(document).ready(function () {
            FileUpload.init();
            var errorMessage = @Html.Raw(Json.Serialize(Model.ErrorMessage));
            var result = @Json.Serialize(Model.Result);
            baseController.actionResult("Save", result, errorMessage, "@(Model.Team.Id == 0 ? ("/Admin/Team/Create") : ("/Admin/Team/Edit/" + Model.Team.Id))");
            let professions = $("#Team_Professions").val().split(',');
            $("#ProfessionList").val(professions);
            $("#ProfessionList").select2({
                placeholder: "Select Profession"
            });
        });

        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        function submitForm() {
            var professions = $("#ProfessionList").val().length > 0 ? $("#ProfessionList").val().join(',') : null;
            $("#Team_Professions").val(professions);
            $("#kt_form").submit();
        }
        var FileUpload = {
            init: function () {
                new KTImageInput("kt_image_1")
            }
        };
    </script>
}

StudioBooking/Areas/Admin/Views/Team/Index.cshtml
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Team Members
                </h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="/Admin/" class="text-muted">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/Admin/Team" class="text-muted">Our Team</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<!--end::Subheader-->
<!--begin::Entry-->
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <!--begin::Card-->
        <div class="card card-custom">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">
                <div class="card-title">
                    <h3 class="card-label">
                        Teams
                        @*<span class="d-block text-muted pt-2 font-size-sm">Sorting &amp; pagination remote datasource</span>*@
                    </h3>
                </div>
                <div class="row align-items-center">
                    <div class="input-icon">
                        <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                        <span>
                            <i class="flaticon2-search-1 text-muted"></i>
                        </span>
                    </div>
                </div>
                <div class="card-toolbar">
                    <!--begin::Button-->
                    <a href="/Admin/Team/Create" class="btn btn-primary font-weight-bolder">
                        <span class="svg-icon svg-icon-md">
                            <!--begin::Svg Icon | path:/metronic/theme/html/demo1/dist/assets/media/svg/icons/Design/Flatten.svg-->
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect x="0" y="0" width="24" height="24" />
                                    <circle fill="#000000" cx="9" cy="15" r="6" />
                                    <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                </g>
                            </svg>
                            <!--end::Svg Icon-->
                        </span>Add New
                    </a>
                    <!--end::Button-->
                </div>
            </div>
            <div class="card-body"> 
                <!--begin: Datatable-->
                <div class="datatable datatable-bordered datatable-head-custom kt-datatable" id="kt_datatable"></div>
                <!--end: Datatable-->
            </div>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
@section scripts{
    <script src="~/js/team.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            TeamDataTable.init();
        });
    </script>
}