StudioBooking/Areas/Admin/Models/TestimonialViewModel.cs
using StudioBooking.DTO;

namespace StudioBooking.Areas.Admin.Models
{
    public class TestimonialViewModel
    {
        public TestimonialDTO Testimonial { get; set; }
        public bool Result { get; set; }
        public string? ErrorMessage { get; set; }
        public TestimonialViewModel()
        {
            Testimonial = new TestimonialDTO();
        }
    }
}

StudioBooking/Areas/Admin/Controllers/TestimonialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudioBooking.Areas.Admin.Models;
using StudioBooking.Data;
using StudioBooking.Data.Models;
using StudioBooking.DTO;
using StudioBooking.Infrastructure;

namespace StudioBooking.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class TestimonialController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly string _filePath;
        public TestimonialController(UserManager<ApplicationUser> userManager, ApplicationDbContext applicationDbContext, IWebHostEnvironment webHostEnvironment) : base(userManager)
        {
            _context = applicationDbContext;
            _webHostEnvironment = webHostEnvironment;
            _filePath = _webHostEnvironment.WebRootPath + AppConfig.ClientImageUrl.Replace("/", "\\");
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View(new TestimonialViewModel());
        }

        public async Task<IActionResult> Edit(int id)
        {
            var testimonialViewModel = new TestimonialViewModel
            {
                Testimonial = await TestimonialDTO.GetTestimonial(_context, id)
            };
            return View("Create", testimonialViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveTestimonial(TestimonialViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var testimonialInDb = await _context.Testimonials.FirstOrDefaultAsync(c => c.Id == model.Testimonial.Id && !c.IsDelete);
                    if (testimonialInDb == null)
                    {

                        var testimonial = new Testimonial
                        {
                            Name = model.Testimonial.Name,
                            Professions = model.Testimonial.Professions,
                            Review = model.Testimonial.Review,
                            Rating = model.Testimonial.Rating,
                            CreatedBy = GetUserId(),
                            CreatedDate = Defaults.GetDateTime(),
                            ModifiedBy = GetUserId(),
                            ModifiedDate = Defaults.GetDateTime(),
                            IsActive = true,
                            Image = model.Testimonial.ImageName != null ? new Common().UploadedFile(model.Testimonial.ImageName, _filePath) : string.Empty,
                        };
                        await _context.Testimonials.AddAsync(testimonial);
                    }
                    else
                    {
                        testimonialInDb.Name = model.Testimonial.Name;
                        testimonialInDb.Review = model.Testimonial.Review;
                        testimonialInDb.Rating = model.Testimonial.Rating;
                        testimonialInDb.Professions = model.Testimonial.Professions;
                        testimonialInDb.ModifiedBy = GetUserId();
                        testimonialInDb.ModifiedDate = Defaults.GetDateTime();
                        testimonialInDb.Image = model.Testimonial.ImageName != null ? new Common().UploadedFile(model.Testimonial.ImageName, _filePath) : testimonialInDb.Image;
                    }
                    await _context.SaveChangesAsync();
                    model.Result = true;
                }
                catch (Exception ex)
                {
                    model.ErrorMessage = ex.Message;
                    model.Result = false;
                }
            }
            return View("Create", model);
        }


        [HttpGet]
        public async Task<IActionResult> GetTestimonials()
        {
            var testimonials = await TestimonialDTO.GetTestimonials(_context, true);
            return Ok(new { data = testimonials });
        }
    }
}

StudioBooking/Areas/Admin/Views/Testimonial/Create.cshtml
@using StudioBooking.Infrastructure;
@model StudioBooking.Areas.Admin.Models.TestimonialViewModel
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Create Testimonial
                </h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="/Admin/" class="text-muted">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/Admin/Testimonial" class="text-muted">Testimonials</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="Admin/Testimonial/Create" class="text-muted"> @(Model.Testimonial.Id == 0 ? "Create Testimonial" : "Update Testimonial")</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<!--end::Subheader-->
<div class="card card-custom card-sticky" id="kt_page_sticky_card">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                @(Model.Testimonial.Id == 0 ? "Create Testimonial" : "Update Testimonial") <i class="mr-2"></i>
                @*<small class="">try to scroll the page</small>*@
            </h3>
        </div>
        <div class="card-toolbar">
            <a href="/Admin/Testimonial" class="btn btn-light-primary font-weight-bolder mr-2">
                <i class="ki ki-long-arrow-back icon-sm"></i>
                Back
            </a>
            <div class="btn-group">
                <button type="button" class="btn btn-primary font-weight-bolder" onclick="submitForm()">
                    <i class="ki ki-check icon-sm"></i>
                    Save
                </button>
            </div>
        </div>
    </div>
    <div class="card-body" style="padding-bottom:0px">
        <!--begin::Form-->
        <form asp-action="SaveTestimonial" asp-area="Admin" asp-controller="Testimonial" method="post" class="form" enctype="multipart/form-data" id="kt_form">
            @Html.HiddenFor(t => t.Testimonial.Id)
            @Html.HiddenFor(t => t.Testimonial.Image)
            <div class="row">
                <div class="col-xl-2"></div>
                <div class="col-xl-8">
                    <div class="form-group row">
                        <label asp-for="Testimonial.Name" class="col-3">Name</label>
                        <div class="col-9">
                            <input asp-for="Testimonial.Name" class="form-control form-control-solid" required="true" placeholder="Name" />
                            <span asp-validation-for="Testimonial.Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Testimonial.Professions" class="col-3">Professions</label>
                        <div class="col-9">
                            <select id="ProfessionList" class="form-control form-control-solid select2" asp-items="Html.GetEnumSelectList<Enums.Professions>()" multiple="multiple">
                            </select>
                            @Html.HiddenFor(t => t.Testimonial.Professions)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Testimonial.Rating" class="col-3">Rating</label>
                        <div class="col-9">
                            <input asp-for="Testimonial.Rating" class="form-control form-control-solid" required="true" placeholder="Rating" />
                            <span asp-validation-for="Testimonial.Rating" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Testimonial.Review" class="col-3">Review</label>
                        <div class="col-9">
                            <textarea asp-for="Testimonial.Review" class="form-control form-control-solid" placeholder="Review" rows="2"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Testimonial.Image" class="col-3">Image</label>
                        <div class="col-9">
                            <div class="image-input image-input-outline" id="kt_image_1">
                                <div class="image-input-wrapper" style="background-image: url('@(string.IsNullOrEmpty(Model.Testimonial.Image) ? Defaults.UploadImage : (AppConfig.ClientImageUrl + Model.Testimonial.Image))')"></div>
                                <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Upload Image">
                                    <i class="fa fa-pen icon-sm text-muted"></i>
                                    <input asp-for="Testimonial.ImageName" accept=".png, .jpg, .jpeg" class="custom-file-input" />
                                </label>
                                <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Discard Image">
                                    <i class="ki ki-bold-close icon-xs text-muted"></i>
                                </span>
                            </div>
                            <span class="form-text text-muted">Allowed file types:  png, jpg, jpeg.</span>
                        </div>
                    </div>
                </div>
                <div class="col-xl-2"></div>
            </div>
        </form>
        <!--end::Form-->
    </div>
</div>
@section Scripts
    {
    <script type="text/javascript">
        var sourceUpdated = false;
        $(document).ready(function () {
            FileUpload.init();
            var errorMessage = @Html.Raw(Json.Serialize(Model.ErrorMessage));
            var result = @Json.Serialize(Model.Result);
            baseController.actionResult("Save", result, errorMessage, "@(Model.Testimonial.Id == 0 ? ("/Admin/Testimonial/Create") : ("/Admin/Testimonial/Edit/" + Model.Testimonial.Id))");
            let professions = $("#Testimonial_Professions").val().split(',');
            $("#ProfessionList").val(professions);
            $("#ProfessionList").select2({
                placeholder: "Select Profession"
            });
        });

        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });

        function submitForm() {
            var professions = $("#ProfessionList").val().length > 0 ? $("#ProfessionList").val().join(',') : null;
            $("#Testimonial_Professions").val(professions);
            $("#kt_form").submit();
        }
        var FileUpload = {
            init: function () {
                new KTImageInput("kt_image_1")
            }
        };
    </script>
}

StudioBooking/Areas/Admin/Views/Testimonial/Index.cshtml
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-6 subheader-solid" id="kt_subheader">
    <div class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <!--begin::Page Title-->
                <h5 class="text-dark font-weight-bold my-1 mr-5">
                    Testimonials
                </h5>
                <!--end::Page Title-->
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold p-0 my-2 font-size-sm">
                    <li class="breadcrumb-item">
                        <a href="/Admin/" class="text-muted">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="/Admin/Testimonial" class="text-muted">Testimonials</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<!--end::Subheader-->
<!--begin::Entry-->
<div class="d-flex flex-column-fluid">
    <!--begin::Container-->
    <div class="container">
        <!--begin::Card-->
        <div class="card card-custom">
            <div class="card-header flex-wrap border-0 pt-6 pb-0">
                <div class="card-title">
                    <h3 class="card-label">
                        Testimonials
                        @*<span class="d-block text-muted pt-2 font-size-sm">Sorting &amp; pagination remote datasource</span>*@
                    </h3>
                </div>
                <div class="row align-items-center">
                    <div class="input-icon">
                        <input type="text" class="form-control" placeholder="Search..." id="kt_datatable_search_query" />
                        <span>
                            <i class="flaticon2-search-1 text-muted"></i>
                        </span>
                    </div>
                </div>
                <div class="card-toolbar">
                    <!--begin::Button-->
                    <a href="/Admin/Testimonial/Create" class="btn btn-primary font-weight-bolder">
                        <span class="svg-icon svg-icon-md">
                            <!--begin::Svg Icon | path:/metronic/theme/html/demo1/dist/assets/media/svg/icons/Design/Flatten.svg-->
                            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                    <rect x="0" y="0" width="24" height="24" />
                                    <circle fill="#000000" cx="9" cy="15" r="6" />
                                    <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                </g>
                            </svg>
                            <!--end::Svg Icon-->
                        </span>Add New
                    </a>
                    <!--end::Button-->
                </div>
            </div>
            <div class="card-body">
                <!--begin: Datatable-->
                <div class="datatable datatable-bordered datatable-head-custom kt-datatable" id="kt_datatable"></div>
                <!--end: Datatable-->
            </div>
        </div>
        <!--end::Card-->
    </div>
    <!--end::Container-->
</div>
<!--end::Entry-->
@section scripts{
    <script src="~/js/testimonial.js" asp-append-version="true"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            TestimonialDataTable.init();
        });
    </script>
}